engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
    checks:
      max_line_length:
        enabled: false
  duplication:
    enabled: true
    exclude_paths:
      - "spec/"
    config:
      languages:
        ruby:
          mass_threshold: 30
        javascript:
exclude_paths:
- config/
- db/
- vendor/